### ISSUE TITLE
coffee

### ISSUE THREAD

**Issue by royeaher** [Justineo/vue-echarts#173] opened 2018-01-16 07:40 UTC
npm throw err "CoffeeScript on NPM has moved to "coffeescript" (no hyphen)"

**Comment by Justineo** [comment] 2018-01-16 08:01
Where does this come from? What command were you trying to run?

**Comment by royeaher** [comment] 2018-01-16 08:11
npm i

**Comment by Justineo** [comment] 2018-01-17 18:17
Cannot reproduce the problem. Can you give more detailed information?

**Comment by royeaher** [comment] 2018-01-21 06:22
Just because of coffeeScript`s repository had moved to another address.vue-cli had same issus and has fixed.

**Comment by Justineo** [comment] 2018-01-21 09:51
OK, so I'm closing this one.

**Closed by Justineo** 2018-01-21 09:51 UTC
